### ISSUE TITLE
broken utf8 chars

### ISSUE THREAD

**Issue by grosser** [basecamp/mail_view#11]
our mails look find in any mailer, but in mail_view they got "fÃ¼r" instead of "für"

**Comment by chrisdebruin** [comment]
just add &lt;meta content="text/html; charset=utf-8" http-equiv="content-type" /&gt; to the head of your mail layouts file

**Comment by jeremy** [comment]
Nasty - could you submit a pull request with the fix?

**Comment by chrisdebruin** [comment]
this has been fix already by this commit e474ec74f387ca413c460a3a912b45ec950f9eef

**Comment by jeremy** [comment]
Indeed! Thanks @chrisdebruin
