### ISSUE TITLE
Publish as a gem

### ISSUE THREAD

**Issue by robink** [basecamp/mail_view#25]
Well, you know, no one wants a new commit to break your application... Using this repo as source in a project Gemfile is just bad practice.

**Comment by geetarista** [comment]
+1 on this. The gem published on rubygems is a fork that is way out of date.

**Comment by akshayrawat** [comment]
Please. Need [this](https://github.com/37signals/mail_view/commit/fb2bb6264e89aa7ff43f1683a3c187d561938e88)

**Comment by kreeger** [comment]
While I agree this ought to be published as a gem, and pointing your Gemfile straight to the git repo is a bad idea, [you could](http://gembundler.com/git.html) use the first 10 characters of a specific commit's SHA to ensure you're always looking at one version of the codebase.

``` ruby
gem 'mail_view', git: 'git://github.com/37signals/mail_view.git', ref: '86a56c5514'
```

But you don't have to take my word for it… _try it!_

**Comment by josh** [comment]
Well, we can't, cause some jerk decided to publish it themselves.

![](http://i.imgur.com/JMu0Z.png)

**Comment by akshayrawat** [comment]
@toreriklinnerud - can you take a look please.

**Comment by geetarista** [comment]
Thanks Akshay. I unfortunately can't use the git version in my Gemfile since my app is partly vendored and it creates a ton of conflicts.

Hopefully he relinquishes it so it can be properly published.

**Comment by toreriklinnerud** [comment]
Hi this is jerk, 

We published the gem at a time when the project looked dead on github. In hindsight we should probably have used a prefix.

@josh I have added you as an owner on rubygems.

**Comment by geetarista** [comment]
Thanks @toreriklinnerud.

**Comment by geetarista** [comment]
Has this been published yet? I can't really tell from Rubygems.

**Comment by toreriklinnerud** [comment]
I have published 1.0.3 which is identical to 37signals/mail_view master except for the gem version.

**Comment by PikachuEXE** [comment]
I suppose this issue could be closed?

**Comment by PikachuEXE** [comment]
Someone please close this issue

**Comment by mcolyer** [comment]
What's included in 1.0.3? Master is currently marked as 1.0.1.

**Comment by toreriklinnerud** [comment]
@mcolyer Everything prior to the bump to 1.0.3 in this branch: https://github.com/toreriklinnerud/mail_view/commits/master 

@packagethief @josh do one of you want to bump the gem version and push it to rubygems? I don't want to cause any further confusion.

**Comment by PikachuEXE** [comment]
So this repo is the official repo but not the gem on `rubygems`?
Quite confusing

**Comment by jeremy** [comment]
Hey @josh - please to be adding me to gem owners.

**Comment by josh** [comment]
I don't think I have access lol

**Comment by jeremy** [comment]
@josh looks like @toreriklinnerud added you :point_right: 

```
Owners for gem: mail_view
- tel@jklm.no
- josh@joshpeek.com
```

**Comment by josh** [comment]
```
$ gem owner mail_view --add jeremy@bitsweat.net
Owner added successfully.
Owners for gem: mail_view
- jeremy@bitsweat.net
- tel@jklm.no
- josh@joshpeek.com
```

**Comment by jeremy** [comment]
txx!
