### ISSUE TITLE
feature request: list the locales in the rails app in a dropdown so you can test multi language emails

### ISSUE THREAD

**Issue by rubytastic** [basecamp/mail_view#29]
feature request: list the locales in the rails app in a dropdown so you can test multi language emails

would be a very cool addition when testing multi locale rails apps.

**Comment by donaldpiret** [comment]
Yeah, been trying to implement this but haven't found out how I can pass parameters to the mail view in any way...

**Comment by rubytastic** [comment]
Haven't looked into this lately had the same problem. Perhaps its an idea to have that language dropdown prefixed and then try to get the locales from Rails be passed to the Preview engine "somehow" ;) ?

**Comment by donaldpiret** [comment]
Just figured this out, the @rack_env is being passed to the MailView. so in your mailview you can do something like:

```
@locale = Rack::Request.new(@rack_env).params["locale"]
```

Then just pass the locale parameter in the url when accessing your mailview (which you can do in an iframe for example).

**Comment by rubytastic** [comment]
Great , you make a commit ? Else I implement this later this week to damn busy right now :(

**Comment by donaldpiret** [comment]
I don't know if this should necessarily be implemented as part of the gem itself. Email translations are completely dependant on the implementation of your mailer methods so I don't think we can build it in a way that will work for everybody in every case. I feel having a wiki page explaining the way you can achieve this would be more beneficial than just trying to set the i18n locale for everyone.

For example, my mailer methods often look like this:

```
I18n.with_locale(@user.locale) do
      mail :to => @user.email_addresses, .....
end
```

**Comment by jeremy** [comment]
+1 @donaldpiret - this depends on how you roll your mailers. Best to handle it in your MailView subclass.
