### ISSUE TITLE
uninitialized constant Notifier::Preview::Notifier

### ISSUE THREAD

**Issue by sc0ttman** [basecamp/mail_view#3]
When I add the route and class to my notifier model, I get the above error when I try to vist one of my preview pages: 'http://0.0.0.0:3000/mail_view/booking' for example.

I'm not sure if I'm doing something wrong. The mail_view folder goes in vendor/plugins correct? I am missing something? 

I'm using Rails 3.0.9. I also had to add tilt to my Gemfile.

**Comment by sc0ttman** [comment]
Okay more strange behavior. When I restart the server (rails server) and visit the url, the HTML versions loads, but when I refresh, I get the error until I restart the server again. 

So, it seems its only able to render the email once. No idea whats going on.

**Comment by sc0ttman** [comment]
Found out you need to call the Notifier like this:
```::Notifier.invitation(inviter, invitee)

```
```

**Comment by travisp** [comment]
I encountered this same issue recently when adding my fifth preview method (it worked fine for the first four). It would display fine on the very first display, and then display this message on every subsequent refresh until server restart.

However, your technique seemed to work around the issue.

**Comment by omarvelous** [comment]
Very Odd... This was working flawlessly prior.... No need to restart, no need to prefix with "::"...

**Comment by rainchen** [comment]
Same issue, prefix with "::" and restart the server is working for me.
version: 1.0.2

**Comment by marcinwieprzkowicz** [comment]
Thanks sc0ttman, yours solution works fine for me :)

**Comment by jeremy** [comment]
Made a note in bc4946edf375d0ee2a797eb7990ab271ce2c76fb
