### ISSUE TITLE
Changes to I18n.locale are not retained in the email_template

### ISSUE THREAD

**Issue by drewB** [basecamp/mail_view#44]
We overrode the default_email_template to customize the layout of the mail view.  Part of that customization is making the field descriptions translatable.  For some reason, I18n.locale is always 'en' in that template even if it is explicitly set in the MailView action.  

Is there somewhere else the locale needs to be set?

**Comment by jeremy** [comment]
This library is locale-agnostic, so there's noplace it needs to be set. You're on your own to get that rolling!
