### ISSUE TITLE
Preview Real Mail

### ISSUE THREAD

**Issue by ryanb** [basecamp/mail_view#5]
What if this came with its own mail delivery method? Then this could also be used to preview the real mail as it would be sent out.

``` ruby
# config/environments/development.rb
config.action_mailer.delivery_method = :mail_view
```

The deliveries would need to persist somewhere, maybe just inside the tmp directory. Then when an email is sent out the URL can be logged for easy preview, maybe even an option to open it with Launchy so it automatically pops up when delivering.

**Comment by turadg** [comment]
+1

**Comment by ryanb** [comment]
This may be out of the scope of mail_view, so I decided to create a gem for doing this called [letter_opener](https://github.com/ryanb/letter_opener).

**Comment by josh** [comment]
@ryanb thats pretty neat. :+1: as its own project.

**Comment by sosedoff** [comment]
Nice, pretty similar to [fakemail](https://github.com/sosedoff/fakemail)
