### ISSUE TITLE
Doesn't update without server restart

### ISSUE THREAD

**Issue by turadg** [basecamp/mail_view#6]
When I'm in :development, most of my classes update in the runtime as I edit their code. But when I edit my Preview class, say to add a new preview method, nothing changes in the browser.

**Comment by atipugin** [comment]
Same for me

**Comment by alejandrodumas** [comment]
Same here

**Comment by sohara** [comment]
Ditto. Would be useful if mail_view's classes/modules weren't cached in non-production environments.

Edit: by that I mean classes that inherit from MailView.

**Comment by halida** [comment]
same here...

**Comment by sethbro** [comment]
Same here. Kind of defeats the purpose when you're attempting to preview changes during development.

**Comment by jeremy** [comment]
This is a hassle. Patches welcome to make the middleware respect dev-mode reloading.

**Comment by adilwali** [comment]
I found this to be frustrating also, but (I think) I'm successfully working around it by adding this to my development.rb: 
config.action_view.cache_template_loading = false

When I do that, no server restarts are needed.  Of course, I don't want that setting on all the time, so I only use it when testing my email templates.  Hope that helps!

**Comment by damienrch** [comment]
Agree. Absolutely useless without this feature. Somebody let me know if they decide to fork a fix and I'll use that, otherwise, might be tempted to create one myself.

**Comment by dhh** [comment]
@damien-roche, you go, girl!

**Comment by damienrch** [comment]
@dhh, ok, not absolutely useless. But 9 months, and still no fix? Is this project abandoned? I fear you may know the inner workings of Rails a little more intimately than me ;)

**Comment by danspencer** [comment]
+1

**Comment by jwarzech** [comment]
@adilwali, This solution worked for me thanks!!!

**Comment by millisami** [comment]
While I'm on rails 3.2, the way @adilwali suggested, it doesn't work for me.
@jwarzech Which version of rails did you use?

**Comment by jwarzech** [comment]
@millisami I am using rails 3.2.9

**Comment by millisami** [comment]
@jwarzech Ok, then I suppose I'll to test it out on 3.2.9 Thanks.

**Comment by PikachuEXE** [comment]
@millisami I have tested it on Rails 3.2.9
It works
What is your result?

BTW is it possible to make it reload the `MailPreview` class without restart?

**Comment by millisami** [comment]
@PikachuEXE Did it work for you without adding the `config.action_view.cache_template_loading = false` in `development.rb` or just installing the gem only?

**Comment by PikachuEXE** [comment]
@millisami Oh removing that config still works for template

But still not the class (`MailPreview` or something)

So this issue is still valid

**Comment by millisami** [comment]
So then I guess have to wait on this issue to be fixed or is there any other forks that solved this?

**Comment by PikachuEXE** [comment]
Is ActionMailer classes supposed to be eager loaded in app and rspec? I forgot

And I cannot find any code related to eager loading...

**Comment by killthekitten** [comment]
Still not fixed, what's the real problem? Should I try to investigate and fix it?

**Comment by PikachuEXE** [comment]
The problem is that the actions of any subclass of `MailView` seem to be preloaded and cached
even on development (with cache config set to `false` of course)
So that when you try to add a new action, it does not show up on refresh of index page (e.g.`/mail_view`)

**Comment by killthekitten** [comment]
@PickachuEXE It can be caused by class constant passed from routes.rb?

**Comment by PikachuEXE** [comment]
I have no idea how `mount` work
So maybe

**Comment by killthekitten** [comment]
@PickachuEXE ok, it's on my todo list now. I'll check later. Same symptoms rails_admin gem has (but it's not a bug, it's kind of expected behavior).

**Comment by PikachuEXE** [comment]
Great to hear that! Thanks!

P.S. You don't need to mention my name every time
I am watching this thread

**Comment by killthekitten** [comment]
That's OK, since I'm twitter addict :+1:

**Comment by scharfie** [comment]
Here's my cheesy workaround to this issue.  Basically, I just route all the requests to the mail view indirectly from a controller.  This allows Rails to reload the mail view class.

``` ruby
# routes
match '/mailers/:mailer(/:name)', :to => "mailers#show"

# controller
class MailersController < ApplicationController
  def show
    request.env.merge!(
      'PATH_INFO'   => params[:name].to_s,
      'SCRIPT_NAME' => url_for(:name => nil)
    )

    mailer = params[:mailer].classify.constantize
    status, headers, body = mailer.call(request.env)
    render :text => body.join('').html_safe
  end
end

# a mail view
class PreviewMailer < MailView
  def some_notification
    # do stuff
  end
end
```

Then hit /mailers/preview_mailer to see the list of actions.

**Comment by PikachuEXE** [comment]
@scharfie It's working! Thanks!
Wonder if this can be included in the gem to solve this bug...

**Comment by PikachuEXE** [comment]
After using this workaround
I got this bug: Mange/roadie#52
It happens often already before using the workaround

**Comment by inspire22** [comment]
@scharfie - nice thanks.  Does this break .txt email handling, or is that my own slim templates / routing issue?  

Make sure it's development only or that's a pretty big security hole.

**Comment by inspire22** [comment]
In case anyone runs into my problem of it not working with text emails, commenting out the format.html {} in _your_ mailer block will render the text mail instead (since it's the only one then).

**Comment by trevorturk** [comment]
Fixed in https://github.com/rails/rails/issues/10685 :tada:

**Comment by thenickcox** [comment]
@trevorturk Wait, is this gem only being maintained as part of the Rails core now?

**Comment by trevorturk** [comment]
@thenickcox, this particular issue turned out to be caused by a Rails bug and was fixed 7 months ago. 

I'm not sure about the maintenance plan for this gem. I'd imagine it'll get some fixes but that the bulk of the work will be directed toward the new "inspired by mail_view" feature in Rails (https://github.com/rails/rails/pull/13332)

**Comment by mayuresh-srivastava** [comment]
How to solve this issue for Rails 5 (Rails 5.1.6 specifically)? 
Because solution provided by @adilwali i.e. config.action_view.cache_template_loading = false not working.

**Comment by PikachuEXE** [comment]
There is email preview in rails now
`::ActionMailer::Preview`
Try to use that

**Comment by mayuresh-srivastava** [comment]
@PikachuEXE Yeah I am using ActionMailer::Preview only.

**Comment by PikachuEXE** [comment]
Then any related issue should be reported to rails repo
