### ISSUE TITLE
Rolling Back Database Changes

### ISSUE THREAD

**Issue by eric1234** [basecamp/mail_view#69]
I don't like to depend on certain data being available in my development database when previewing mail. So I add the data the preview operates on when running the preview. But this means my development database is getting a constant stream of data every time I view my e-mail. I added the following to my class to wrap everything in a transaction and rollback at the end. But was wondering if there is a more obvious way that I missed?

```
def call env
  ret = nil
  begin
    ActiveRecord::Base.transaction do
      ret = super
      raise ActiveRecord::Rollback
    end
  rescue ActiveRecord::Rollback
  end
  ret
end
```

**Comment by jeremy** [comment]
@eric1234 This is a perfect fit for `db/seeds.rb` :grin:

**Comment by eric1234** [comment]
K, thanks for the feedback. Sounds like the way I want to use it just isn't supported by mail_view so my override of "call" that I posted above is the best solution.

`db/seeds.rb` seems less ideal for me because it is not immediately obvious that the data created in `db/seeds.rb` is for mail testing. Also it is not obvious in the mail testing that the data is defined in `db/seeds.rb`. Same problem I have with Rails traditional fixtures. I prefer to define my test data in my tests rather than in a separate area of the code base. Same principal with mail_view for me. But different strokes for different folks. Just wanted to make sure I wasn't missing anything obvious.
