### ISSUE TITLE
Is this a gem or how do use this with my application?

### ISSUE THREAD

**Issue by alphaone** [basecamp/mail_view#7]
I tried to install "mail_view" as a gem, with no success. How do use 'mail_view' in my app? Maybe the readme.md should be clearer in that way.

**Comment by jankubr** [comment]
Put this in your Gemfile:

group :test, :development do
  gem 'mail_view', :git => "git://github.com/37signals/mail_view.git"
end

**Comment by grosser** [comment]
fixed in https://github.com/37signals/mail_view/pull/10

**Comment by jeremy** [comment]
Made a note about adding it to your Gemfile in 750cbd8bea04139380d2bc98edb031f42820b3ba
