### ISSUE TITLE
Adopt more "the Rails way"-like usage

### ISSUE THREAD

**Issue by sidonath** [basecamp/mail_view#8]
The README suggests that MailView is something similar to the unit tests for emails but with visual output. Then it goes on to suggest we should embed preview generation code directly into our code clases. While the suggested organization makes it easier to get started, it's not something seen very often in the Rails land (thinking specifically about test/spec code here).

I suggest to adopt usage more along the lines of the Rails way, ie. code organization more similar to that of tests and specs.

In my local integration, I organized preview code in following manner:

```
app/
  mailers/
    notification_mailer.rb ← defines NotificationMailer < ActionMailer::Base
mail_views/
  notification_mailer_preview.rb ← defines NotificationMailerPreview < MailView
```

Here we have application-level dir "mail_views" (in line of specs/tests) in which there is an .rb file for every mailer (eg. notifier_mailer_preview.rb) with a definition of MailerPreview class (eg. `NotifierMailerPreview < MailVew`). It then contains one or more method for every method in the original Mailer class.

If any organization is standardized it would be easy to automatically generate routes, but that's a topic for another issue.

**Comment by jeremy** [comment]
Thanks for the suggestion!

In this case, having the "example" mail setup next to the mailers themselves has worked out great.
